env:
  es2021: true
  node: true
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  ecmaVersion: latest
  sourceType: "module"
  babelOptions:
    plugins:
      - "@babel/plugin-syntax-import-assertions"
extends: "eslint:recommended"
rules: {}
ignorePatterns: ['*.spec.js']
