SPI=org.geotools.data.postgis.PostgisNGDataStoreFactory
host=__DATABASE_HOST__
port=__DATABASE_PORT__
database=__DATABASE_NAME__
schema=__DATABASE_SCHEMA__
user=__DATABASE_USER__
passwd=__DATABASE_PASSWORD__
Loose\ bbox=true
Estimated\ extends=false
validate\ connections=true
Connection\ timeout=10
preparedStatements=true
