allowedEPSGCodes: [
  '3857',
  '4326',
  '3035'
]
allowedExtent: [
  [
    5.85,
    47.27,
  ],
  [
    15.02,
    55.07
  ]
]
allowedDataTypes: [
  'Byte',
  'Int16',
  'Float32'
]
minFilesize: 1000
maxFilesize: 10000000
